# Generated by Django 2.2.1 on 2019-05-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeMaster',
            fields=[
                ('CollegeID', models.AutoField(primary_key=True, serialize=False)),
                ('CollegeCode', models.CharField(max_length=10, null=True)),
                ('CollegeName', models.CharField(max_length=50, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.IntegerField()),
                ('ModifiedBy', models.IntegerField()),
            ],
        ),
    ]
