# Generated by Django 2.2.1 on 2019-06-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmaster',
            name='middle_Name',
        ),
    ]
