# Generated by Django 2.2.1 on 2019-06-11 06:44

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmaster',
            name='studentID',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='departmentID', chained_model_field='departmentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SignupMaster'),
        ),
    ]
