# Generated by Django 2.2.1 on 2019-06-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmaster',
            name='studentID',
        ),
        migrations.DeleteModel(
            name='SignupMaster',
        ),
    ]
