# Generated by Django 2.2.1 on 2019-06-11 06:50

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190611_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMaster',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('pdf1', models.FileField(upload_to='app/upload')),
                ('pdf2', models.FileField(upload_to='app/upload')),
                ('pdf3', models.FileField(upload_to='app/upload')),
                ('pdf4', models.FileField(upload_to='app/upload')),
                ('collegeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CollegeMaster')),
                ('departmentID', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='programID', chained_model_field='programID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DepartmentMaster')),
                ('programID', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='collegeID', chained_model_field='collegeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProgramMaster')),
                ('streamID', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='departmentID', chained_model_field='departmentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StreamMaster')),
                ('studentID', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='departmentID', chained_model_field='departmentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SignupMaster')),
            ],
        ),
    ]
