# Generated by Django 2.2.1 on 2019-05-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190530_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentCode', models.CharField(max_length=50)),
                ('DepartmentName', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('ModifiedBy', models.IntegerField()),
                ('collegeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CollegeMaster')),
            ],
        ),
    ]
