# Generated by Django 2.2.1 on 2019-06-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190614_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmaster',
            name='collegeID',
        ),
        migrations.RemoveField(
            model_name='signupmaster',
            name='departmentID',
        ),
        migrations.RemoveField(
            model_name='signupmaster',
            name='programID',
        ),
        migrations.RemoveField(
            model_name='signupmaster',
            name='streamID',
        ),
        migrations.AddField(
            model_name='signupmaster',
            name='Branch',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='signupmaster',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
