# Generated by Django 2.2.1 on 2019-05-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_departmentmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmaster',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='departmentmaster',
            name='ModifiedBy',
        ),
    ]
