# Generated by Django 2.2.1 on 2019-06-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_projecttypemaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttypemaster',
            old_name='Type',
            new_name='ProjectType',
        ),
        migrations.AddField(
            model_name='programmaster',
            name='NumberOfSemester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
