# Generated by Django 2.2.1 on 2019-06-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190613_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmaster',
            name='NumberOfSemester',
            field=models.IntegerField(null=True),
        ),
    ]
