# Generated by Django 2.2.1 on 2019-05-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_programmaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentMaster',
        ),
    ]
