# Generated by Django 2.2.1 on 2019-06-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190613_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMaster',
            fields=[
                ('ProcessID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('ProcessName', models.CharField(max_length=50)),
                ('Processowner', models.CharField(default='T & P Committee', max_length=200)),
                ('ProjRegToBeDoneBy', models.IntegerField(choices=[(1, 'Student'), (2, 'Faculty')])),
                ('ProjHasToBe', models.IntegerField(choices=[(1, 'Always Internal'), (2, 'Always External'), (3, 'Either')])),
                ('ProjShallBeDoneBy', models.IntegerField(choices=[(1, 'Individual'), (2, 'Team'), (3, 'Either')])),
                ('NumberOfStages', models.IntegerField()),
                ('InternalFaculty_Involvement_Needed', models.BooleanField(default=True)),
                ('FacultyRequired', models.BooleanField(default=True)),
                ('HODRequired', models.BooleanField(default=True)),
                ('PrincipalRequired', models.BooleanField()),
                ('PanelReviewRequired', models.BooleanField()),
                ('ExternalGuideNeeded', models.CharField(choices=[(1, 'Not needed'), (2, 'Always needed'), (3, 'Always needed'), (4, 'only if project done externally')], default='----', max_length=200)),
                ('ExternalMentor', models.CharField(choices=[(1, 'Not needed'), (2, 'Always needed'), (3, 'Only if project done externally')], default='----', max_length=200)),
                ('FundingToBeProvided', models.BooleanField()),
                ('ExpenseTrackingRequired', models.BooleanField()),
                ('MaterialToBeProvided', models.BooleanField()),
                ('FinalSubmissionEvaluated', models.BooleanField()),
                ('IsActive', models.BooleanField(default=True)),
                ('ProgramName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProgramMaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('ProjectId', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('IsExternalProject', models.BooleanField()),
                ('TermLead', models.IntegerField(default=0)),
                ('Status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=2)),
                ('CollegeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CollegeMaster')),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DepartmentMaster')),
                ('ProcessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProcessMaster')),
            ],
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=50, unique=True)),
                ('CreatedBy', models.IntegerField(default=0)),
                ('ModifiedBy', models.IntegerField(default=0)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageMaster',
            fields=[
                ('StageID', models.AutoField(primary_key=True, serialize=False)),
                ('StageName', models.CharField(max_length=50)),
                ('StageSeq', models.IntegerField()),
                ('ReqAnyUpload', models.BooleanField(default=True)),
                ('ActivityUpload', models.CharField(max_length=50)),
                ('RequireAnyApproval', models.BooleanField(default=True)),
                ('InternalApprovalType', models.CharField(choices=[(1, 'All'), (2, 'One'), (3, 'either')], default='----', max_length=200)),
                ('IsWorkflowDriven', models.BooleanField(default=True)),
                ('ExternalGuideApprovalNeeded', models.BooleanField(default=True)),
                ('MentorApprovalNeeded', models.BooleanField(default=True)),
                ('PanelApprovalNeeded', models.BooleanField(default=True)),
                ('DeanApprovalNeeded', models.BooleanField(default=True)),
                ('RequireNoDueCertificate', models.BooleanField(default=True)),
                ('CompletionCertiIssuedForStage', models.BooleanField(default=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('ProcessID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProcessMaster')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectTypeMaster',
        ),
    ]
