# Generated by Django 2.2.1 on 2019-05-30 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_departmentmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentCode', models.CharField(max_length=50)),
                ('DepartmentName', models.CharField(max_length=100)),
                ('collegeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CollegeMaster')),
            ],
        ),
    ]
