# Generated by Django 2.2.1 on 2019-06-14 03:27

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190614_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeMaster',
            fields=[
                ('ProjectTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('InSemester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('ProjectType', models.CharField(max_length=20, null=True)),
                ('collegeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CollegeMaster')),
                ('departmentID', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='programID', chained_model_field='programID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DepartmentMaster')),
                ('programID', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='collegeID', chained_model_field='collegeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProgramMaster')),
                ('streamID', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='departmentID', chained_model_field='departmentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StreamMaster')),
            ],
        ),
        migrations.RemoveField(
            model_name='processmaster',
            name='ProgramName',
        ),
        migrations.RemoveField(
            model_name='projectmaster',
            name='CollegeId',
        ),
        migrations.RemoveField(
            model_name='projectmaster',
            name='DepartmentId',
        ),
        migrations.RemoveField(
            model_name='projectmaster',
            name='ProcessId',
        ),
        migrations.DeleteModel(
            name='RoleMaster',
        ),
        migrations.RemoveField(
            model_name='stagemaster',
            name='ProcessID',
        ),
        migrations.DeleteModel(
            name='ProcessMaster',
        ),
        migrations.DeleteModel(
            name='ProjectMaster',
        ),
        migrations.DeleteModel(
            name='StageMaster',
        ),
    ]
