# Generated by Django 2.2.1 on 2019-05-30 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_departmentmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmaster',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='programmaster',
            name='CreatedDate',
        ),
        migrations.RemoveField(
            model_name='programmaster',
            name='IsActive',
        ),
        migrations.RemoveField(
            model_name='programmaster',
            name='ModifiedBy',
        ),
        migrations.RemoveField(
            model_name='programmaster',
            name='ModifiedDate',
        ),
        migrations.AddField(
            model_name='programmaster',
            name='collegeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CollegeMaster'),
        ),
    ]
