# Generated by Django 2.2.1 on 2019-05-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190530_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmaster',
            old_name='collegeID',
            new_name='CollegeID',
        ),
        migrations.RenameField(
            model_name='programmaster',
            old_name='collegeID',
            new_name='CollegeID',
        ),
    ]
