# Generated by Django 2.2.1 on 2019-05-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190530_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmaster',
            name='ProgramID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProgramMaster'),
        ),
        migrations.AlterField(
            model_name='departmentmaster',
            name='CollegeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CollegeMaster'),
        ),
    ]
