# Generated by Django 2.2.1 on 2019-05-30 10:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190530_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmaster',
            name='ProgramID',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='CollegeID', on_delete=django.db.models.deletion.CASCADE, to='app.ProgramMaster'),
        ),
    ]
