# Generated by Django 2.2.1 on 2019-05-31 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190530_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmaster',
            old_name='CollegeID',
            new_name='collegeID',
        ),
        migrations.RenameField(
            model_name='programmaster',
            old_name='CollegeID',
            new_name='collegeID',
        ),
        migrations.RemoveField(
            model_name='departmentmaster',
            name='ProgramID',
        ),
        migrations.AddField(
            model_name='departmentmaster',
            name='programID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProgramMaster'),
        ),
    ]
