# Generated by Django 2.2.1 on 2019-05-31 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190531_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmaster',
            name='programID',
        ),
    ]
