# Generated by Django 2.2.1 on 2019-05-31 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_departmentmaster_programid'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmaster',
            name='programID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProgramMaster'),
        ),
    ]
