# Generated by Django 2.2.1 on 2019-06-03 16:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_departmentmaster_programid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmaster',
            name='programID',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='collegeID', chained_model_field='collegeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProgramMaster'),
        ),
        migrations.CreateModel(
            name='StreamMaster',
            fields=[
                ('StreamID', models.AutoField(primary_key=True, serialize=False)),
                ('StreamCode', models.CharField(max_length=10, null=True)),
                ('StreamName', models.CharField(max_length=30, null=True)),
                ('collegeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CollegeMaster')),
                ('departmentID', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='collegeID', chained_model_field='collegeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DepartmentMaster')),
                ('programID', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='collegeID', chained_model_field='collegeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProgramMaster')),
            ],
        ),
    ]
